version: "3.1"

services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    container_name: ${ADMINER_CONTAINER_NAME}
    image: ${ADMINER_IMAGE}
    restart: always
    ports:
      - ${ADMINER_PORT}:9100
    command:
      - 'php'
      - '-S'
      - '[::]:9100'
      - '-t'
      - '/var/www/html'
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER}
      ADMINER_DESIGN: ${ADMINER_DESIGN}

  api:
    container_name: ${API_CONTAINER_NAME}
    build: .
    env_file:
      - ${ENV_FILE}
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      POSTGRES_HOST: ${POSTGRES_HOST_DOCKER}
    ports:
      - ${API_PORT}:9000
    depends_on:
      - postgres
    restart: on-failure

networks:
  default:
    name: ${NETWORK_NAME}
    external: ${NETWORK_EXTERNAL}
